### ISSUE TITLE
nvidia driver file error

### ISSUE THREAD

**Issue by Yeah2333** [ColorfulSS/docker-ubuntu-gnome-nomachine#1]
![image](https://user-images.githubusercontent.com/22851247/163383800-d206f486-9ab6-4583-b96c-3b40795fedab.png)
这个问题咋解决？没有通过curl下到驱动吗

**Comment by ColorfulSS** [comment]
是的，应该是显卡类型选择问题，Tesla系列显卡和GeForce系列显卡驱动的下载地址不同！
需要选择显卡驱动类型处选择对应你的显卡是Tesla还是GeForce

**Comment by Yeah2333** [comment]
我的显卡是3090，也选择的GeForce。看报错似乎是下载地址404.
![image](https://user-images.githubusercontent.com/22851247/163807915-feed34fc-30d5-4d34-b50b-4ece10a3b518.png)。不过我试了一下这个sh的逻辑好像有问题，输入GeForce但实际不执行GeForce的setting sh

**Comment by ColorfulSS** [comment]
> 我的显卡是3090，也选择的GeForce。看报错似乎是下载地址404. ![image](https://user-images.githubusercontent.com/22851247/163807915-feed34fc-30d5-4d34-b50b-4ece10a3b518.png)。不过我试了一下这个sh的逻辑好像有问题，输入GeForce但实际不执行GeForce的setting sh

这个docker容器内使用该脚本安装的显卡驱动是和宿主机一致的，可能是宿主机显卡驱动版本太新（或者宿主机驱动不是使用官方的sh文件安装的），导致在如下网站找不到相应的版本号的驱动：
https://download.nvidia.com/XFree86/Linux-x86_64/

正常情况宿主机使用官网的sh文件安装的驱动能够在上述网址中自动下载，例如：脚本自动下载驱动链接为https://download.nvidia.cn/XFree86/Linux-x86_64/510.60.02/NVIDIA-Linux-x86_64-510.60.02.run （宿主机驱动版本510.60.02）

不过不应该出现这个问题的啊，我在我的3090上测试了是正常下载和安装的，可以检查下宿主机安装驱动的方式，尽量使用官网的run文件安装

**Comment by ColorfulSS** [comment]
> 

是的，我重新检查了下，脚本判断GeForce部分少写了一个空格。导致任何输入都会使用Tesla的安装脚本，进而导致无法获取到正确的下载连接。感谢指出，问题已修复 ColorfulSS@26126f2ea0a505172d9f1135987de9d2ec9197bf
