### ISSUE TITLE
NoMachine黑屏问题

### ISSUE THREAD

**Issue by PIKACHUIM** [ColorfulSS/docker-ubuntu-gnome-nomachine#2]
大佬您好，我按照您的教程，通过nomachine进行连接，进入桌面黑屏
可以输入账号密码登录，但登录后桌面黑屏只显示鼠标，麻烦大佬看看
主机硬件：`DELL R720XD X79; E5-2696V2; nVidia Tesla K80 ESXi7.0U2`
主机系统：`Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-30-generic x86_64)`
容器系统：`colorfulsky/ubuntu-gnome-nomachine:20.04`

![_%YW 0CZ}V1SRI8YDS4TYOF](https://user-images.githubusercontent.com/40362270/196078014-60a99d71-2586-4523-b485-a308d1188e5f.png)

**Comment by PIKACHUIM** [comment]
另外，希望能和大佬共同开发这个脚本，添加自定义端口映射和网页选择生成

**Comment by hunterkeith2017** [comment]
> 大佬您好，我按照您的教程，通过nomachine进行连接，进入桌面黑屏 可以输入账号密码登录，但登录后桌面黑屏只显示鼠标，麻烦大佬看看 主机硬件：`DELL R720XD X79; E5-2696V2; nVidia Tesla K80 ESXi7.0U2` 主机系统：`Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-30-generic x86_64)` 容器系统：`colorfulsky/ubuntu-gnome-nomachine:20.04`
> 
> ![_%YW 0CZ}V1SRI8YDS4TYOF](https://user-images.githubusercontent.com/40362270/196078014-60a99d71-2586-4523-b485-a308d1188e5f.png)

我的也是，连好了代开就是黑屏

**Comment by QYlichuyou** [comment]
> > 大佬您好，我按照您的教程，通过nomachine进行连接，进入桌面黑屏 可以输入账号密码登录，但登录后桌面黑屏只显示鼠标，麻烦大佬看看 主机硬件：`DELL R720XD X79; E5-2696V2; nVidia Tesla K80 ESXi7.0U2` 主机系统：`Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-30-generic x86_64)` 容器系统：`colorfulsky/ubuntu-gnome-nomachine:20.04`
> > ![_%YW 0CZ}V1SRI8YDS4TYOF](https://user-images.githubusercontent.com/40362270/196078014-60a99d71-2586-4523-b485-a308d1188e5f.png)
> 
> 我的也是，连好了代开就是黑屏

用VNC连接如何呢

**Comment by ColorfulSS** [comment]
> 大佬您好，我按照您的教程，通过nomachine进行连接，进入桌面黑屏 可以输入账号密码登录，但登录后桌面黑屏只显示鼠标，麻烦大佬看看 主机硬件：`DELL R720XD X79; E5-2696V2; nVidia Tesla K80 ESXi7.0U2` 主机系统：`Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-30-generic x86_64)` 容器系统：`colorfulsky/ubuntu-gnome-nomachine:20.04`
> 
> ![_%YW 0CZ}V1SRI8YDS4TYOF](https://user-images.githubusercontent.com/40362270/196078014-60a99d71-2586-4523-b485-a308d1188e5f.png)

你好，Tesla系列应该不会遇到黑屏的问题的，因为没有相关日志报错，我不能够确定问题所在，是否能吧/etc/X11/下的Log文件放出来看下呢？ 如果还有类似的需求的话可以回复下，同时很欢迎能够一起开发和完善这个工作，有需要可以邮件联系，我们再添加其他联系方式：glyou@mail.ustc.edu.cn

**Comment by ColorfulSS** [comment]
> > 大佬您好，我按照您的教程，通过nomachine进行连接，进入桌面黑屏 可以输入账号密码登录，但登录后桌面黑屏只显示鼠标，麻烦大佬看看 主机硬件：`DELL R720XD X79; E5-2696V2; nVidia Tesla K80 ESXi7.0U2` 主机系统：`Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-30-generic x86_64)` 容器系统：`colorfulsky/ubuntu-gnome-nomachine:20.04`
> > ![_%YW 0CZ}V1SRI8YDS4TYOF](https://user-images.githubusercontent.com/40362270/196078014-60a99d71-2586-4523-b485-a308d1188e5f.png)
> 
> 我的也是，连好了代开就是黑屏

显卡型号是什么呢？

**Comment by ColorfulSS** [comment]
> > > 大佬您好，我按照您的教程，通过nomachine进行连接，进入桌面黑屏 可以输入账号密码登录，但登录后桌面黑屏只显示鼠标，麻烦大佬看看 主机硬件：`DELL R720XD X79; E5-2696V2; nVidia Tesla K80 ESXi7.0U2` 主机系统：`Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-30-generic x86_64)` 容器系统：`colorfulsky/ubuntu-gnome-nomachine:20.04`
> > > ![_%YW 0CZ}V1SRI8YDS4TYOF](https://user-images.githubusercontent.com/40362270/196078014-60a99d71-2586-4523-b485-a308d1188e5f.png)
> > 
> > 
> > 我的也是，连好了代开就是黑屏
> 
> 用VNC连接如何呢

VNC的话ubuntu会慢一些，所以建议使用nomachine连接，速度非常流畅。
