### ISSUE TITLE
NoMachine 8 新版本不支持--egl-capture

### ISSUE THREAD

**Issue by LingZichao** [ColorfulSS/docker-ubuntu-gnome-nomachine#3]
https://github.com/ColorfulSS/docker-ubuntu-gnome-nomachine/blob/26c13d68ab848c23f34356717c2fd2f461d6a347/2-remote-virtual-desktops/nx/ubuntu-20.04-gnome-nomachine/Dockerfile#L62

更改成 `--eglcapture` 就可以了

**Comment by ColorfulSS** [comment]
很棒的修改，大家如果有8的需求可以按照这位佬的方案~
