### ISSUE TITLE
进入远程桌面后，无法登录进系统

### ISSUE THREAD

**Issue by tiger7chan** [ColorfulSS/docker-ubuntu-gnome-nomachine#4]
你好，启动你的docker镜像后，通过nomachine连接上了远程桌面，但是再登录界面中，输入了正确的密码，也一直提示"invaid password, please try again"，可以确认密码是正确的，请问这个问题你碰到过没？谢谢

![image](https://github.com/user-attachments/assets/39292887-5ab6-4cb9-9d0b-08d8c2adcefe)

**Comment by ColorfulSS** [comment]
这里提示的是输入用户名后再输入密码，要不你试试？同时还不行的话就新建一个用户试试。还没遇到过这种登陆不上去的问题
